### ISSUE TITLE
README references invalid testchain branch

### ISSUE THREAD

**Issue by ysangkok** [DriveNetTESTDRIVE/DriveNet#15]
The README contains the text:

> For an example sidechain implementation, see: https://github.com/drivechain-project/bitcoin/tree/sidechainBMM

But this link does not work. Should the testchain branch be linked?

**Comment by CryptAxe** [comment]
Sorry for the confusion and not getting back to you quickly. Work has actually all moved to the https://github.com/drivechain-project repository now. The readme there should indeed be updated, however the name of the sidechain repo right now is https://github.com/drivechain-project/sidechains. We've been trying to reorganize things and keep everything in the https://github.com/drivechain-project to avoid confusion or people looking in the wrong place and I'm sorry that it wasn't clear. 

It would be great if you opened a pull request to link to https://github.com/drivechain-project/sidechains in the README for the mainchain (drivenet) repo on the  https://github.com/drivechain-project page.

**Comment by ysangkok** [comment]
Closing this because it was on the wrong repo as noted.
